name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Clojure
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.2.790

    - name: Install dependencies
      run: clojure -P

    - name: Run tests
      run: clojure -X:test

    - name: Build
      run: clojure -X:uberjar

    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build
